//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperSofProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.HistoryProduct = new HashSet<HistoryProduct>();
            this.PrioritySupply = new HashSet<PrioritySupply>();
            this.ProductBid = new HashSet<ProductBid>();
            this.ProductSale = new HashSet<ProductSale>();
            this.SaleAgent = new HashSet<SaleAgent>();
        }
    
        public int ID { get; set; }
        public string Name_Comp { get; set; }
        public Nullable<int> ID_Type_Agent { get; set; }
        public string Ur_Dress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string FIO_director { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual TypeAgent TypeAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryProduct> HistoryProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrioritySupply> PrioritySupply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBid> ProductBid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleAgent> SaleAgent { get; set; }
    }
}
