//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperSofProject.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class USDDDEntities : DbContext
    {
        public USDDDEntities()
            : base("name=USDDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Change> Change { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<HistoryMater> HistoryMater { get; set; }
        public virtual DbSet<HistoryProduct> HistoryProduct { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<NameSale> NameSale { get; set; }
        public virtual DbSet<NameSupply> NameSupply { get; set; }
        public virtual DbSet<PrioritySupply> PrioritySupply { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductBid> ProductBid { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterial { get; set; }
        public virtual DbSet<ProductSale> ProductSale { get; set; }
        public virtual DbSet<SaleAgent> SaleAgent { get; set; }
        public virtual DbSet<ShiftSchedule> ShiftSchedule { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<TypeAgent> TypeAgent { get; set; }
        public virtual DbSet<TypeEmployee> TypeEmployee { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
        public virtual DbSet<TypeSpec> TypeSpec { get; set; }
        public virtual DbSet<TypeSupplier> TypeSupplier { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
    }
}
