//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperSofProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAgent
    {
        public int ID { get; set; }
        public Nullable<int> ID_Sale { get; set; }
        public Nullable<int> ID_Agent { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual NameSale NameSale { get; set; }
    }
}
