//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperSofProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftSchedule
    {
        public int ID { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ID_Change { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> ID_Equipment { get; set; }
    
        public virtual Change Change { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
